FROM node:18.17.1

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY ./public ./public
COPY ./src ./src

CMD npx wait-port metadata:80 && \
    npx wait-port history:80 && \
    npm start