version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: awsstorage
      buildspec: build.yml
      env:
        variables:
          APP_NAME: awsstorage
      ignore-failure: false
    - identifier: gateway
      buildspec: build.yml
      env:
        variables:
          APP_NAME: gateway
      ignore-failure: false
    - identifier: history
      buildspec: build.yml
      env:
        variables:
          APP_NAME: history
      ignore-failure: false
    - identifier: metadata
      buildspec: build.yml
      env:
        variables:
          APP_NAME: metadata
      ignore-failure: false
    - identifier: videostreaming
      buildspec: build.yml
      env:
        variables:
          APP_NAME: videostreaming
      ignore-failure: false
    - identifier: videoupload
      buildspec: build.yml
      env:
        variables:
          APP_NAME: videoupload
      ignore-failure: false

