version: 0.2
batch:
  fast-fail: false
  build-list:
    - identifier: gateway
      env:
        variables:
          APP_NAME: gateway
      buildspec: |
        version: 0.2
        artifacts:
          files: 
            - $APP_NAME.txt
        phases:
          pre_build:
            commands:
              - echo Logging in to Amazon ECR...
              - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
          build:
            commands:
              - sleep 5
              - echo Building the Docker image $APP_NAME...          
              - docker build -t $IMAGE_REPO_NAME:$APP_NAME --file ./$APP_NAME/Dockerfile-prod ./$APP_NAME
              - docker tag $IMAGE_REPO_NAME:$APP_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$APP_NAME
              - echo "$APP_NAME data" > $APP_NAME.txt
              - echo "$APP_NAME completed successfully."
          post_build:
            commands:
              - sleep 5
              - echo Pushing the Docker image $APP_NAME...
              - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$APP_NAME
      ignore-failure: false
    - identifier: videostreaming
      env:
        variables:
          APP_NAME: videostreaming
      buildspec: |
        version: 0.2
        artifacts:
          files: 
            - $APP_NAME.txt
        phases:
          pre_build:
            commands:
              - sleep 180
              - echo Logging in to Amazon ECR...
              - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
          build:
            commands:
              - sleep 5
              - echo Building the Docker image $APP_NAME...          
              - docker build -t $IMAGE_REPO_NAME:$APP_NAME --file ./$APP_NAME/Dockerfile-prod ./$APP_NAME
              - docker tag $IMAGE_REPO_NAME:$APP_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$APP_NAME
              - echo "$APP_NAME data" > $APP_NAME.txt
              - echo "$APP_NAME completed successfully."
          post_build:
            commands:
              - sleep 5
              - echo Pushing the Docker image $APP_NAME...
              - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$APP_NAME
      ignore-failure: false
    - identifier: videoupload
      env:
        variables:
          APP_NAME: videoupload
      buildspec: |
        version: 0.2
        artifacts:
          files: 
            - $APP_NAME.txt
        phases:
          pre_build:
            commands:
              - sleep 360
              - echo Logging in to Amazon ECR...
              - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
          build:
            commands:
              - sleep 5
              - echo Building the Docker image $APP_NAME...          
              - docker build -t $IMAGE_REPO_NAME:$APP_NAME --file ./$APP_NAME/Dockerfile-prod ./$APP_NAME
              - docker tag $IMAGE_REPO_NAME:$APP_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$APP_NAME
              - echo "$APP_NAME data" > $APP_NAME.txt
              - echo "$APP_NAME completed successfully."
          post_build:
            commands:
              - sleep 5
              - echo Pushing the Docker image $APP_NAME...
              - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$APP_NAME
      ignore-failure: false
    - identifier: history
      env:
        variables:
          APP_NAME: history
      buildspec: |
        version: 0.2
        artifacts:
          files: 
            - $APP_NAME.txt
        phases:
          pre_build:
            commands:
              - sleep 540
              - echo Logging in to Amazon ECR...
              - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
          build:
            commands:
              - sleep 5
              - echo Building the Docker image $APP_NAME...          
              - docker build -t $IMAGE_REPO_NAME:$APP_NAME --file ./$APP_NAME/Dockerfile-prod ./$APP_NAME
              - docker tag $IMAGE_REPO_NAME:$APP_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$APP_NAME
              - echo "$APP_NAME data" > $APP_NAME.txt
              - echo "$APP_NAME completed successfully."
          post_build:
            commands:
              - sleep 5
              - echo Pushing the Docker image $APP_NAME...
              - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$APP_NAME
      ignore-failure: false
    - identifier: metadata
      env:
        variables:
          APP_NAME: metadata
      buildspec: |
        version: 0.2
        artifacts:
          files: 
            - $APP_NAME.txt
        phases:
          pre_build:
            commands:
              - sleep 720
              - echo Logging in to Amazon ECR...
              - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
          build:
            commands:
              - sleep 5
              - echo Building the Docker image $APP_NAME...          
              - docker build -t $IMAGE_REPO_NAME:$APP_NAME --file ./$APP_NAME/Dockerfile-prod ./$APP_NAME
              - docker tag $IMAGE_REPO_NAME:$APP_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$APP_NAME
              - echo "$APP_NAME data" > $APP_NAME.txt
              - echo "$APP_NAME completed successfully."
          post_build:
            commands:
              - sleep 5
              - echo Pushing the Docker image $APP_NAME...
              - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$APP_NAME
      ignore-failure: false
    - identifier: awsstorage
      env:
        variables:
          APP_NAME: awsstorage
      buildspec: |
        version: 0.2
        artifacts:
          files: 
            - $APP_NAME.txt
        phases:
          pre_build:
            commands:
              - sleep 900
              - echo Logging in to Amazon ECR ...
              - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
          build:
            commands:
              - sleep 5
              - echo Building the Docker image $APP_NAME...          
              - docker build -t $IMAGE_REPO_NAME:$APP_NAME --file ./$APP_NAME/Dockerfile-prod ./$APP_NAME
              - docker tag $IMAGE_REPO_NAME:$APP_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$APP_NAME
              - echo "$APP_NAME data" > $APP_NAME.txt
              - echo "$APP_NAME completed successfully."
          post_build:
            commands:
              - sleep 5
              - echo Pushing the Docker image $APP_NAME ...
              - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$APP_NAME
      ignore-failure: false



  artifacts:
  files:
    - "*/**"