version: 0.2
batch:
  fast-fail: false
  build-list:
    - identifier: gateway
      env:
        variables:
          APP_NAME: gateway
      buildspec: |
        version: 0.2
        artifacts:
          files: 
            - $APP_NAME.txt
        phases:
          pre_build:
            commands:
              - sleep 2
              - echo Logging in to Amazon ECR...
              - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
          build:
            commands:
              - sleep 5
              - echo Building the Docker image $APP_NAME...          
              - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG --file ./$APP_NAME/Dockerfile-prod ./$APP_NAME
              - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
              - echo "$APP_NAME data" > $APP_NAME.txt
              - echo "$APP_NAME completed successfully."
          post_build:
            commands:
              - sleep 10
              - echo Pushing the Docker image $APP_NAME...
              - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
    - identifier: videoupload
      env:
        variables:
          APP_NAME: videoupload
      buildspec: |
        version: 0.2
        artifacts:
          files: 
            - $APP_NAME.txt
        phases:
          pre_build:
            commands:
              - sleep 40
              - echo Logging in to Amazon ECR...
              - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
          build:
            commands:
              - sleep 45
              - echo Building the Docker image $APP_NAME...          
              - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG --file ./$APP_NAME/Dockerfile-prod ./$APP_NAME
              - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
              - echo "$APP_NAME data" > $APP_NAME.txt
              - echo "$APP_NAME completed successfully."
          post_build:
            commands:
              - sleep 51
              - echo Pushing the Docker image $APP_NAME...
              - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      ignore-failure: false

  artifacts:
  files:
    - "*/**"