#
# To deploy:
#
# kubectl apply -f scripts/deploy.yaml
#
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-storage
  template:
    metadata:
      labels:
        app: video-storage
    spec:
      containers: 
      - name: video-storage
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: {{ .Values.service.targetPort }}
        - name: STORAGE_REGION
          value: {{ .Values.storage.region }}
        - name: STORAGE_NAME
          value: {{ .Values.storage.name }}
        - name: STORAGE_FOLDER_NAME
          value: {{ .Values.storage.folder }}
        - name: STORAGE_ACCESS_KEY
          value: {{ .Values.storage.key }}
        - name: STORAGE_SECRET_ACCESS_KEY
          value: {{ .Values.storage.secret }}
---
apiVersion: v1
kind: Service
metadata:
  name: video-storage
spec:
  selector:
    app: video-storage
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
